[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/mlavrinenko/flibrarian"
readme = "README.md"
keywords = ["fb2", "library", "book"]
categories = ["command-line-utilities"]

[workspace.lints.rust]
unsafe_code = "forbid"
unused = { level = "deny", priority = -1 }

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }

module_name_repetitions = "allow"
multiple_crate_versions = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"

[profile.dev]
codegen-units = 256
debug = "line-tables-only"
split-debuginfo = "unpacked"

[profile.test]
codegen-units = 256
debug = "line-tables-only"
split-debuginfo = "unpacked"
