[package]
name = "flibrarian-core"
description = "Core library for interacting with fb2 zipped libraries"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
base64 = "0.22"
duckdb = { version = "1.4" }
env_logger = "0.11.8"
fb2 = "0.4.4"
zip = "4.0.0"
quick-xml = { version = "0.38.3", features = ["overlapped-lists", "serialize"] }
log = "0.4.27"
memchr = "2"
rayon = "1.10.0"
regex = "1.11.1"
uuid = { version = "1.17.0", features = ["v4"] }
chardetng = "0.1.17"
encoding_rs = { version = "0.8.35", features = ["fast-legacy-encode"] }
encoding_rs_io = "0.1.7"
dirs = "6"
toml = "0.8"
fake = { version = "3", features = ["derive"], optional = true }
rand = { version = "0.8", optional = true }

[features]
bundled-duckdb = ["duckdb/bundled"]
faking = ["dep:fake", "dep:rand"]

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
iai-callgrind = "0.10"
tempfile = "3"
rand = "0.8"

[[bench]]
name = "indexing"
harness = false
required-features = ["faking"]

[[bench]]
name = "indexing_iai"
harness = false
required-features = ["faking"]

[lints]
workspace = true
