pub const FIRST_NAMES_EN: &[&str] = &[
    "James",
    "Mary",
    "John",
    "Patricia",
    "Robert",
    "Jennifer",
    "Michael",
    "Linda",
    "William",
    "Elizabeth",
    "David",
    "Barbara",
    "Richard",
    "Susan",
    "Joseph",
    "Jessica",
    "Thomas",
    "Sarah",
    "Charles",
    "Karen",
    "Christopher",
    "Lisa",
    "Daniel",
    "Nancy",
    "Matthew",
    "Betty",
    "Anthony",
    "Margaret",
    "Mark",
    "Sandra",
    "Donald",
    "Ashley",
    "Steven",
    "Dorothy",
    "Paul",
    "Kimberly",
    "Andrew",
    "Emily",
    "Joshua",
    "Donna",
];

pub const LAST_NAMES_EN: &[&str] = &[
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Rodriguez",
    "Martinez",
    "Hernandez",
    "Lopez",
    "Gonzalez",
    "Wilson",
    "Anderson",
    "Thomas",
    "Taylor",
    "Moore",
    "Jackson",
    "Martin",
    "Lee",
    "Perez",
    "Thompson",
    "White",
    "Harris",
    "Sanchez",
    "Clark",
    "Ramirez",
    "Lewis",
    "Robinson",
    "Walker",
    "Young",
    "Allen",
    "King",
    "Wright",
    "Scott",
    "Torres",
    "Nguyen",
    "Hill",
    "Flores",
];

pub const FIRST_NAMES_RU: &[&str] = &[
    "Александр",
    "Мария",
    "Дмитрий",
    "Анна",
    "Сергей",
    "Елена",
    "Андрей",
    "Ольга",
    "Алексей",
    "Наталья",
    "Владимир",
    "Ирина",
    "Михаил",
    "Татьяна",
    "Иван",
    "Екатерина",
    "Николай",
    "Светлана",
    "Евгений",
    "Юлия",
    "Павел",
    "Галина",
    "Пётр",
    "Людмила",
    "Виктор",
    "Вера",
    "Борис",
    "Надежда",
    "Григорий",
    "Любовь",
];

pub const LAST_NAMES_RU: &[&str] = &[
    "Иванов",
    "Петров",
    "Сидоров",
    "Козлов",
    "Новиков",
    "Морозов",
    "Волков",
    "Соколов",
    "Попов",
    "Лебедев",
    "Кузнецов",
    "Смирнов",
    "Фёдоров",
    "Васильев",
    "Павлов",
    "Семёнов",
    "Голубев",
    "Виноградов",
    "Богданов",
    "Воробьёв",
    "Жуков",
    "Тихонов",
    "Крылов",
    "Белов",
    "Медведев",
    "Никитин",
    "Орлов",
    "Комаров",
    "Захаров",
    "Макаров",
];

pub const MIDDLE_NAMES_RU: &[&str] = &[
    "Александрович",
    "Дмитриевич",
    "Сергеевич",
    "Андреевич",
    "Алексеевич",
    "Владимирович",
    "Михайлович",
    "Иванович",
    "Николаевич",
    "Евгеньевич",
    "Павлович",
    "Петрович",
    "Викторович",
    "Борисович",
    "Григорьевич",
    "Александровна",
    "Дмитриевна",
    "Сергеевна",
    "Андреевна",
    "Алексеевна",
    "Владимировна",
    "Михайловна",
    "Ивановна",
    "Николаевна",
    "Евгеньевна",
];

pub const GENRES: &[&str] = &[
    "sf_fantasy",
    "sf",
    "sf_space",
    "sf_cyberpunk",
    "detective",
    "thriller",
    "prose_classic",
    "prose_contemporary",
    "prose_history",
    "prose_rus_classic",
    "adventure",
    "humor_prose",
    "love_contemporary",
    "love_history",
    "sci_history",
    "sci_philosophy",
    "sci_biology",
    "sci_physics",
    "child_tale",
    "child_adv",
    "poetry",
    "dramaturgy",
    "ref_guide",
    "ref_encyclopedia",
    "religion",
    "nonfiction",
    "comp_programming",
    "military_history",
];

pub const TITLE_ADJECTIVES: &[&str] = &[
    "Dark",
    "Silent",
    "Eternal",
    "Forgotten",
    "Last",
    "Hidden",
    "Burning",
    "Crystal",
    "Iron",
    "Golden",
    "Silver",
    "Broken",
    "Ancient",
    "Frozen",
    "Sacred",
    "Crimson",
    "Hollow",
    "Endless",
    "Lost",
    "Shattered",
];

pub const TITLE_NOUNS: &[&str] = &[
    "Tower", "Kingdom", "Shadow", "Storm", "Throne", "Crown", "Blade", "Forest", "River",
    "Mountain", "Dragon", "Phoenix", "Star", "Moon", "Empire", "Garden", "Mirror", "Legend",
    "Secret", "Path",
];

pub const SEQUENCE_NAMES: &[&str] = &[
    "Chronicles of the Realm",
    "The Dark Saga",
    "Legacy Series",
    "Tales of the Forgotten",
    "The Iron Collection",
    "Legends Untold",
    "The Crystal Archives",
    "Shadows of Time",
    "The Golden Path",
    "Echoes of Eternity",
];
